import PDFDocument from 'pdfkit';
import type { RequestHandler } from './$types';

export const GET: RequestHandler = async ({ url }) => {
	// const min = Number(url.searchParams.get('min') ?? '0');
	// const max = Number(url.searchParams.get('max') ?? '1');
    const doc = new PDFDocument();

    let buffers:any[] = [];

    // Collect data as the PDF is being generated
    doc.on('data', (chunk) => buffers.push(chunk));

    // Return a Promise that resolves when the PDF is fully generated
    await new Promise((resolve) => {
        doc.on('end', resolve); 

        /** start add content to the PDF */
        // here is where we we need to RnD
        doc.text('Hello, this is a PDF generated by PDFKit!');
        doc.addPage();
        doc.text('This is the second page');
        /** end add content to the PDF */

        // Finalize the PDF and end the stream
        doc.end();
    });

    // Concatenate all the chunks into a single buffer
    const pdfData = Buffer.concat(buffers);

    // Return the PDF as a response
    return new Response(pdfData, {
        headers: {
            'Content-Type': 'application/pdf',
            'Content-Disposition': 'inline' // open in page
            // 'Content-Disposition': 'attachment' // direct download
        }
    });
};